import { Router } from "express";
import { addIncome, addExpense, deleteTransaction, currentBalance, getAllTransactions, totalExpense, totalIncome,getOneMonthTransaction,getAllExpenseTransactions,getAllIncomeTransactions } from "../controllers/transaction.controller";
const router = Router();
router.get('/currentbalance',currentBalance);
router.get('/totalincome',totalIncome);
router.get('/totalexpenses',totalExpense);
router.get('/getalltransactions',getAllTransactions);
router.get('/expensetransactions',getAllExpenseTransactions);
router.get('/incometransactions',getAllIncomeTransactions);
router.get('/getonemonthtransaction',getOneMonthTransaction);
router.post("/addincome", addIncome);
router.post("/addexpense", addExpense);
router.delete('/:id',deleteTransaction);
export default router;
